### ISSUE TITLE
Wejście na stronę ze stacjownika

### ISSUE THREAD

**Issue by jasieleczeq** [Thundo54/tablice-td2#11]
Jeśli się wejdzie na stronę przez wybraniu stacji w stacjowniku (np. https://tablice-td2.web.app/?station=Tarkowice), to pociągi pokazują się dopiero po kliknięciu przycisku do zmiany tablicy (Przyjazdy/Odjazdy).

**Comment by Thundo54** [comment]
Bug naprawiony - powodował go brak synchronizacji pobierania danych z ich wyświetlaniem (dokładniej z danymi z API tablic)
